### ISSUE TITLE
Failed to proxy package JSON from remote : cached-path-relative

### ISSUE THREAD

**Issue by jorwalk** [ashaffer/cached-path-relative#1]
Has this package been removed from NPM? 

I am getting an npm ERR! 404 failed to proxy package JSON from remote : cached-path-relative

'cached-path-relative' is not in the npm registry.

You should bug the author to publish it (or use the name yourself!) 
It was specified as a dependency of 'module-deps'

**Comment by ashaffer** [comment]
Has it? It's visible on NPM here: https://www.npmjs.com/package/cached-path-relative and I don't have a problem installing it. Are you using an NPM proxy or something?

**Comment by jorwalk** [comment]
For some reason, on that day NPM was have issues. For some odd reason your module was throwing that error. Bear in mind, that was the same day the huge DDOS attack took place. Glad to have it squared away.

Thank you for following up. I will mark this issue as closed.
